return {
    SECTION_RESOURCE = '[[Resources|Resource]]',
        ROW_TYPE = 'Type',
        ROW_RARITY = 'Rarity',
        ROW_COMBUSTIBLE = 'Usable as fuel',
    SECTION_ITEM = '[[Items|Item]]',
        ROW_WEIGHT = 'Weight',
        ROW_STACK_SIZE = 'Stack size',
            ROW_STACK_SIZE_TOOLTIP = 'Stack sizes can be configured in server configuration.',
        ROW_SPOILS = 'Spoilage',
            ROW_SPOILS_TO_IN_N_F = 'to %s in %s',
            ROW_SPOILS_TO_IN_UNKNOWN_F = 'to %s in unknown time',
            ROW_SPOILS_TO_UNKNOWN_IN_N_F = 'to an unknown item in %s',
    SECTION_HEXAGON_STORE = '[[HLN-A (Genesis)#Hexagon Exchange|Hexagon Exchange]]',
        ROW_HEXAGON_PURCHASE_AMOUNT = 'Exchange yields',
            ROW_HEXAGON_PURCHASE_AMOUNT_VALUE_F = '%d pieces',
        ROW_HEXAGON_PURCHASE_COST = 'At price',
    SECTION_SPAWN_COMMANDS = '[[Console commands|Spawn commands]]',
}
